context:
  version: "0.23.1"

package:
  name: openai-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openai-agents/openai_agents-${{ version }}.tar.gz
    sha256: 2bbd0a87a42531d25638529396644defd3ff2afd92fd9ec7d2f02167e5458a99

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - openai >=3,<4
    - pydantic >=2.12.2,<3
    - griffelib >=2,<3
    - typing-extensions >=4.12.2,<5
    - requests >=2.0,<3
    - types-requests >=2.0,<3
    - websockets >=15.0,<17
    - mcp >=1.19.0,<3
    - httpx2

tests:
  - python:
      imports:
        - agents
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A lightweight, powerful framework for multi-agent workflows
  homepage: https://github.com/openai/openai-agents-python
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - timkpaine
    - moritzwilksch
