context:
  version: "0.5.1"

package:
  name: openai-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openai-agents/openai_agents-${{ version }}.tar.gz
    sha256: e193cd3a1b0d4f9a3f3fa9c4011c0b1f8876fa5f38bde4ae41d6a834a5791124

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - openai >=2.2,<3
    - pydantic >=2.10,<3
    - griffe >=1.5.6,<2
    - typing-extensions >=4.12.2,<5
    - requests >=2.0,<3
    - types-requests >=2.0,<3
    - mcp >=1.11.0,<2

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - agents
      pip_check: true

about:
  summary: A lightweight, powerful framework for multi-agent workflows
  homepage: https://github.com/openai/openai-agents-python
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - timkpaine
    - moritzwilksch
