context:
  version: 0.0.3

package:
  name: openai-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openai-agents/openai_agents-${{ version }}.tar.gz
    sha256: f0958b94e775aa3b50c00309896fb1a009823c785bc9a6d0a0b853149f5b5ce6

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - griffe >=1.5.6,<2
    - openai >=1.66.2
    - pydantic >=2.10,<3
    - requests >=2.0,<3
    - types-requests >=2.0,<3
    - typing-extensions >=4.12.2,<5

tests:
  - python:
      python_version: ${{ python_min }}
      imports:
        - agents
      pip_check: true

about:
  summary: A lightweight, powerful framework for multi-agent workflows
  homepage: https://github.com/openai/openai-agents-python
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - moritzwilksch
