context:
  version: "0.0.14"

package:
  name: openai-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openai-agents/openai_agents-${{ version }}.tar.gz
    sha256: 884d6a1d4be7e77c2442b3ed058abe2c56231a6a05942fe87c6d8ecee72ca491

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - griffe >=1.5.6,<2
    - openai >=1.66.2
    - pydantic >=2.10,<3
    - requests >=2.0,<3
    - types-requests >=2.0,<3
    - typing-extensions >=4.12.2,<5

tests:
  - python:
      python_version: ${{ python_min }}
      imports:
        - agents
      pip_check: true

about:
  summary: A lightweight, powerful framework for multi-agent workflows
  homepage: https://github.com/openai/openai-agents-python
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - moritzwilksch
