context:
  version: "0.2.10"

package:
  name: openai-agents
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/o/openai-agents/openai_agents-${{ version }}.tar.gz
    sha256: 8741890b5b5f1513589aebc571776b9a17158a01f6df55ab6402668d2a204a4d

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - openai >=1.99.6,<2
    - pydantic >=2.10,<3
    - griffe >=1.5.6,<2
    - typing-extensions >=4.12.2,<5
    - requests >=2.0,<3
    - types-requests >=2.0,<3
    - mcp >=1.11.0,<2

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - agents
      pip_check: true

about:
  summary: A lightweight, powerful framework for multi-agent workflows
  homepage: https://github.com/openai/openai-agents-python
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - timkpaine
    - moritzwilksch
